# dotfiles
* Dotfiles
This is a quick and dirty way to organise my dotfiles.

** Current Doom Info

here's my infodump:
#+begin_quote
generated  Sep 24, 2025 15:21:04
system     MacOS 26.0 Darwin 25.0.0 arm64 ns
emacs      30.2 EMACSDIR=~/.config/emacs/
           EMACS=/opt/homebrew/Cellar/emacs-plus@30/30.2/Emacs.app/Contents/MacOS/Emacs
doom       3.0.0-pre PROFILE=_default@0 HEAD -> master 7e711d53c 2025-09-22 23:30:03
           -0400 ~/.config/doom/
shell      /bin/zsh
features   ACL DBUS GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG LCMS2 LIBXML2 MODULES
           NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF
           TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM XWIDGETS ZLIB
traits     gui server-running envvar-file custom-file
custom     connection-local-criteria-alist connection-local-profile-alist
           safe-local-variable-values package-selected-packages org-agenda-files
           elfeed-feeds
modules    :config use-package :completion (corfu +icons +dabbrev +orderless) (vertico
           +childframe +icons) :ui doom doom-dashboard (emoji +ascii +github +unicode)
           hl-todo indent-guides (ligatures +extra) minimap modeline nav-flash ophints
           (popup +defaults) smooth-scroll (treemacs +lsp) unicode (vc-gutter +pretty)
           vi-tilde-fringe (window-select +numbers) workspaces (zen +mixed-pitch-mode
           +writeroom-mode) :editor (evil +everywhere) file-templates fold (format
           +onsave) rotate-text snippets (&nopath whitespace +guess +trim) word-wrap
           :emacs (dired +dirvish +icons) electric eww (ibuffer +icons) tramp undo vc
           :term vterm :checkers (syntax +childframe +flymake +icons) (spell +flyspell
           +enchant +everywhere) grammar :tools (debugger +lsp) direnv docker
           editorconfig ein (eval +overlay) (lookup +dictionary +offline +docsets) llm
           (lsp +peek) (magit +forge) pdf tmux tree-sitter :os macos tty :lang (cc
           +lsp +tree-sitter) data (elixir +tree-sitter +lsp) emacs-lisp (erlang +lsp
           +tree-sitter) (go +lsp +tree-sitter) (graphql +lsp) (json +tree-sitter
           +lsp) (java +tree-sitter +lsp) (javascript +lsp +tree-sitter) (latex
           +cdlatex +fold +lsp) (markdown +grip) (org +dragndrop +gnuplot +hugo
           +journal +jupyter +noter +pandoc +pomodoro +present +pretty) plantuml
           graphviz (python +conda +cython +lsp +poetry +pyright +tree-sitter) (rest
           +jq) (sh +lsp +tree-sitter) (web +lsp +tree-sitter) (yaml +lsp
           +tree-sitter) :app calendar everywhere (rss +org +youtube) :config (default
           +gnupg +bindings +smartparens)
packages   (magit :recipe (:host github :repo magit/magit :branch main)) (hl-todo)
           (blamer) (magit-todos) (circadian) (ob-mermaid) (org-modern) (toc-org)
           (tree-sitter) (tree-sitter-langs) (org-pdftools :recipe (:host github :repo
           fuxialexander/org-pdftools)) (org-noter-pdftools :recipe (:host github
           :repo fuxialexander/org-pdftools :files (org-noter-pdftools.el)))
elpa       tablist pdf-tools org-pdftools org-noter-pdftools org-noter
#+end_quote

To enjoy the performance benefits of emacs 30, as well as to avoid some bugs and enjoy more modus themes, I've moved away from using the railwaycat port and am using the emacsplus port of emacs (for macos).

Refer to [[https://github.com/d12frosted/homebrew-emacs-plus?tab=readme-ov-file#install][this README for emacsplus port]].

** MacOS Specific
*** TODO Creating launchd service for emacs-daemon
Motivation:
I'm on MacOS now and am running emacs that on the doom starter pack.
My workflows involve creating frames for discrete contexts instead of just using the workspaces feature. This allows me to put windows in different virtual desktop for separating out these contexts and aiding my context-switching.

I would really like to setup emacsclient properly here, but the available info seems outdated on how to do so. Current [[https://www.emacswiki.org/emacs/EmacsAsDaemon#h5o-11][emacswiki entry]] on the daemon.

[[https://systemcrafters.net/emacs-tips/using-the-emacs-daemon/][Systemcrafter's blog post]] might be useful as well.

- [[https://web.archive.org/web/20091207041756/http://cubiclemuses.com/cm/articles/2009/08/06/emacs-and-os-x-launchd][ref]]
  Also, launchctl has changed, see [[https://gist.github.com/masklinn/a532dfe55bdeab3d60ab8e46ccc38a68][this gist]] to understand instead:

  #+begin_src bash
# validate plist file using this:
# plutil -lint /path/to/your/plist/file.plist
plutil -lint /Library/LaunchAgents/gnu.emacs.daemon.plist
  #+end_src

  #+begin_src bash
# launchctl has new syntax for loading plist
# sudo launchctl bootstrap system /Library/LaunchDaemons/com.example.service.plist

sudo launchctl bootstrap system  /Library/LaunchAgents/gnu.emacs.daemon.plist
  #+end_src
